create database CarrosAntiguos;

\l

\c CarrosAntiguos;

--creacion de tablas
CREATE TABLE CARRO(
	ID_PLACA VARCHAR(6) PRIMARY KEY,
	MARCA varchar(20) NOT NULL,
	MODELO INT NOT NULL,
	COLOR VARCHAR(10) NOT NULL,
	VALOR FLOAT NOT NULL
)
CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE_COMP VARCHAR(30) NOT NULL,
	APELLIDO_COM VARCHAR(30) NOT NULL,
	DIRECCION VARCHAR(20) NOT NULL,
	TELEFONO INTEGER(10) NOT NULL
)
CREATE TABLE PAIS(
	COD_PAIS INT PRIMARY KEY,
	NOM_PAIS VARCHAR(15) NOT NULL,
)
CREATE TABLE CARRO_PAIS(
	ID_CLIENTE VARCHAR(10),
	COD_PAIS INT,	
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY (COD_PAIS) REFERENCES PAIS(COD_PAIS)
)
CREATE TABLE COMPRA(
	ID_COMPRA INT PRIMARY KEY
	FEC_COMP DATE NOT NULL,
	VALOR_COMP FLOAT NOT NULL,
	ID_CLIENTE INT,
	ID_PLACA VARCHAR (6),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY (ID_PLACA) REFERENCES CARRO(ID_PLACA)
)
CREATE TABLE VENTA(
	ID_VENTA INT PRIMARY KEY
	FEC_VENT DATE NOT NULL,
	VALOR FLOAT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PLACA VARCHAR(6),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY (ID_PLACA) REFERENCES CARRO(ID_PLACA)
)
CREATE TABLE EVENTO(
	ID_EVENTO INT PRIMARY KEY,
	NOMBRE_EVENTO VARCHAR(20) NOT NULL,
	ID_PLACA VARCHAR(6)
	FOREIGN KEY (ID_PLACA) REFERENCES CARRO(ID_PLACA)
)
